// ANETrainingEngine.m — Full Stories110M training engine for iPhone ANE
// Ported from macOS ANE-Training/training/train_large.m
// Core loop: compile kernels → forward+backward on ANE → Adam update → recompile
#import "ANETrainingEngine.h"
#import "ANETrainingConfig.h"
#import "ANEStoriesMIL.h"
#import "ANEStoriesCPUOps.h"
#import <Accelerate/Accelerate.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <dispatch/dispatch.h>

// iOS-specific overrides (ANETrainingConfig.h has base defines)
#define IOS_ACCUM_STEPS ACCUM_STEPS
#define IOS_MAX_COMPILES MAX_COMPILES

// All structs, defines, and helpers come from ANETrainingConfig.h
// (LayerWeights, LayerAdam, LayerActs, LayerGrads, LayerKernels,
//  WQ_SZ, WO_SZ, W1_SZ, W2_SZ, W3_SZ, SCORE_CH, etc.)

// Duplicate local definitions removed — using ANETrainingConfig.h versions.
// The following section was auto-generated by agent and is now deleted.
// Jump to: struct ANETrainState

#if 0 // BEGIN DISABLED DUPLICATES
typedef struct {
    float *Wq, *Wk, *Wv, *Wo;
    float *W1, *W2, *W3;
    float *rms_att, *rms_ffn;
} LayerWeights;

typedef struct {
    float *m, *v;
    size_t n;
} AdamState;

typedef struct {
    AdamState Wq, Wk, Wv, Wo;
    AdamState W1, W2, W3;
    AdamState rms_att, rms_ffn;
} LayerAdam;

// Per-layer activation buffers (saved for backward)
typedef struct {
    float *layer_in;
    float *xnorm;
    float *Q, *K, *V;
    float *attn_out;
    float *o_out;
    float *x2;
    float *x2norm;
    float *h1, *h3;
    float *silu_out;
    float *ffn_out;
} LayerActs;

// Per-layer gradient accumulators
typedef struct {
    float *Wq, *Wk, *Wv, *Wo;
    float *W1, *W2, *W3;
    float *rms_att, *rms_ffn;
} LayerGrads;

// ANE kernels per layer
typedef struct {
    Kern *fwdAttn, *fwdFFN, *ffnBwd, *sdpaBwd1, *qkvBwd;
} LayerKernels;

// llama2.c model file header
typedef struct {
    int dim, hidden_dim, n_layers, n_heads, n_kv_heads, vocab_size, seq_len;
} Llama2Config;

// Checkpoint header
typedef struct {
    int magic;
    int version;
    int step, total_steps;
    int n_layers, vocab_size, dim, hidden_dim, n_heads, seq_len;
    float lr, loss;
    int adam_t;
    int pad[5];
} CkptHdr;

// ===== Alloc helpers =====
static AdamState adam_alloc(size_t n) {
    AdamState s; s.m = (float*)calloc(n, 4); s.v = (float*)calloc(n, 4); s.n = n; return s;
}
static void adam_free(AdamState *s) { free(s->m); free(s->v); }

static LayerWeights layer_weights_alloc(void) {
    LayerWeights w;
    w.Wq = (float*)malloc(WQ_SZ*4); w.Wk = (float*)malloc(WQ_SZ*4);
    w.Wv = (float*)malloc(WQ_SZ*4); w.Wo = (float*)malloc(WO_SZ*4);
    w.W1 = (float*)malloc(W1_SZ*4); w.W2 = (float*)malloc(W2_SZ*4); w.W3 = (float*)malloc(W3_SZ*4);
    w.rms_att = (float*)malloc(DIM*4); w.rms_ffn = (float*)malloc(DIM*4);
    return w;
}
static void layer_weights_free(LayerWeights *w) {
    free(w->Wq); free(w->Wk); free(w->Wv); free(w->Wo);
    free(w->W1); free(w->W2); free(w->W3);
    free(w->rms_att); free(w->rms_ffn);
}

static LayerAdam layer_adam_alloc(void) {
    LayerAdam a;
    a.Wq = adam_alloc(WQ_SZ); a.Wk = adam_alloc(WQ_SZ);
    a.Wv = adam_alloc(WQ_SZ); a.Wo = adam_alloc(WO_SZ);
    a.W1 = adam_alloc(W1_SZ); a.W2 = adam_alloc(W2_SZ); a.W3 = adam_alloc(W3_SZ);
    a.rms_att = adam_alloc(DIM); a.rms_ffn = adam_alloc(DIM);
    return a;
}
static void layer_adam_free(LayerAdam *a) {
    adam_free(&a->Wq); adam_free(&a->Wk); adam_free(&a->Wv); adam_free(&a->Wo);
    adam_free(&a->W1); adam_free(&a->W2); adam_free(&a->W3);
    adam_free(&a->rms_att); adam_free(&a->rms_ffn);
}

static LayerActs layer_acts_alloc(void) {
    LayerActs a;
    a.layer_in = (float*)malloc(SEQ*DIM*4);
    a.xnorm = (float*)malloc(SEQ*DIM*4); a.Q = (float*)malloc(SEQ*DIM*4);
    a.K = (float*)malloc(SEQ*DIM*4); a.V = (float*)malloc(SEQ*DIM*4);
    a.attn_out = (float*)malloc(SEQ*DIM*4); a.o_out = (float*)malloc(SEQ*DIM*4);
    a.x2 = (float*)malloc(SEQ*DIM*4); a.x2norm = (float*)malloc(SEQ*DIM*4);
    a.h1 = (float*)malloc(SEQ*HIDDEN*4); a.h3 = (float*)malloc(SEQ*HIDDEN*4);
    a.silu_out = (float*)malloc(SEQ*HIDDEN*4); a.ffn_out = (float*)malloc(SEQ*DIM*4);
    return a;
}
static void layer_acts_free(LayerActs *a) {
    free(a->layer_in); free(a->xnorm); free(a->Q); free(a->K); free(a->V);
    free(a->attn_out); free(a->o_out); free(a->x2); free(a->x2norm);
    free(a->h1); free(a->h3); free(a->silu_out); free(a->ffn_out);
}

static LayerGrads layer_grads_alloc(void) {
    LayerGrads g;
    g.Wq = (float*)calloc(WQ_SZ, 4); g.Wk = (float*)calloc(WQ_SZ, 4);
    g.Wv = (float*)calloc(WQ_SZ, 4); g.Wo = (float*)calloc(WO_SZ, 4);
    g.W1 = (float*)calloc(W1_SZ, 4); g.W2 = (float*)calloc(W2_SZ, 4); g.W3 = (float*)calloc(W3_SZ, 4);
    g.rms_att = (float*)calloc(DIM, 4); g.rms_ffn = (float*)calloc(DIM, 4);
    return g;
}
static void layer_grads_zero(LayerGrads *g) {
    memset(g->Wq, 0, WQ_SZ*4); memset(g->Wk, 0, WQ_SZ*4);
    memset(g->Wv, 0, WQ_SZ*4); memset(g->Wo, 0, WO_SZ*4);
    memset(g->W1, 0, W1_SZ*4); memset(g->W2, 0, W2_SZ*4); memset(g->W3, 0, W3_SZ*4);
    memset(g->rms_att, 0, DIM*4); memset(g->rms_ffn, 0, DIM*4);
}
static void layer_grads_free(LayerGrads *g) {
    free(g->Wq); free(g->Wk); free(g->Wv); free(g->Wo);
    free(g->W1); free(g->W2); free(g->W3);
    free(g->rms_att); free(g->rms_ffn);
}

// ===== IOSurface helpers not in ANETrainingConfig.h =====
static void io_copy(IOSurfaceRef dst, int dst_ch, IOSurfaceRef src, int src_ch, int channels, int sp) {
    IOSurfaceLock(dst, 0, NULL);
    IOSurfaceLock(src, kIOSurfaceLockReadOnly, NULL);
    memcpy((_Float16*)IOSurfaceGetBaseAddress(dst) + dst_ch * sp,
           (_Float16*)IOSurfaceGetBaseAddress(src) + src_ch * sp,
           channels * sp * sizeof(_Float16));
    IOSurfaceUnlock(src, kIOSurfaceLockReadOnly, NULL);
    IOSurfaceUnlock(dst, 0, NULL);
}
static void io_write_fp16_at(IOSurfaceRef s, int ch_off, const float *data, int channels, int sp) {
    IOSurfaceLock(s, 0, NULL);
    cvt_f32_f16((_Float16*)IOSurfaceGetBaseAddress(s) + ch_off * sp, data, channels * sp);
    IOSurfaceUnlock(s, 0, NULL);
}
#endif // END DISABLED DUPLICATES

// llama2.c model file header (for loading pretrained weights)
typedef struct {
    int dim, hidden_dim, n_layers, n_heads, n_kv_heads, vocab_size, seq_len;
} Llama2Config;

// Checkpoint header
typedef struct {
    int magic;          // 0x424C5A54 "BLZT"
    int version;        // 2
    int step, total_steps;
    int n_layers, vocab_size, dim, hidden_dim, n_heads, seq_len;
    float lr, loss;
    double cum_compile, cum_train, cum_wall;
    int cum_steps, cum_batches;
    int adam_t;
    int pad[3];
} CkptHdr;

// ===== Training state =====
struct ANETrainState {
    LayerWeights lw[NLAYERS];
    LayerAdam la[NLAYERS];
    LayerActs acts[NLAYERS];
    LayerGrads grads[NLAYERS];
    LayerKernels kern[NLAYERS];
    Kern *sdpaBwd2[NLAYERS];

    // Global weights
    float *rms_final;
    float *embed;           // [VOCAB, DIM] row-major

    // Global gradient accumulators
    float *grms_final;
    float *gembed;
    AdamState arms_final;
    AdamState aembed;

    // Scratch buffers
    float *x_cur;           // [DIM, SEQ] current activation
    float *x_final;         // [DIM, SEQ] after final rmsnorm
    float *logits;          // [VOCAB, SEQ]
    float *dlogits;         // [VOCAB, SEQ]
    float *dy;              // [DIM, SEQ] gradient flowing backward
    float *dffn;
    float *dh1, *dh3;
    float *dx_ffn;
    float *dx2;
    float *do_out_buf;
    float *dq, *dk, *dv;
    float *dx_attn;

    // Token data (mmap'd)
    uint16_t *token_data;
    size_t n_tokens;
    size_t data_len;
    int data_fd;

    // Training state
    int step;
    int total_steps;
    int adam_t;
    float lr;
    float last_loss;
    int accum_count;        // steps within current accumulation batch
    int compile_count;      // track compiles for iOS budget reset

    // Concurrency
    dispatch_queue_t dw_q;
    dispatch_group_t dw_grp;

    // Status
    bool kernels_compiled;
    bool compiling;
};

// ===== Compile helpers (ported from train_large.m lines 59-100) =====
static bool compile_layer_kernels(LayerKernels *lk, LayerWeights *w, int *compile_count) {
    lk->fwdAttn = compile_kern(gen_sdpa_fwd_taps(), (@{
        @"@model_path/weights/rms1.bin": @{@"offset":@0, @"data":build_blob(w->rms_att, 1, DIM)},
        @"@model_path/weights/wq.bin":   @{@"offset":@0, @"data":build_blob(w->Wq, DIM, DIM)},
        @"@model_path/weights/wk.bin":   @{@"offset":@0, @"data":build_blob(w->Wk, DIM, DIM)},
        @"@model_path/weights/wv.bin":   @{@"offset":@0, @"data":build_blob(w->Wv, DIM, DIM)},
        @"@model_path/weights/wo.bin":   @{@"offset":@0, @"data":build_blob(w->Wo, DIM, DIM)},
        @"@model_path/weights/mask.bin": @{@"offset":@0, @"data":get_mask_blob()},
    }), DIM*SEQ*2, 6*DIM*SEQ*2);

    lk->fwdFFN = compile_kern(gen_ffn_fwd_taps(), (@{
        @"@model_path/weights/rms2.bin": @{@"offset":@0, @"data":build_blob(w->rms_ffn, 1, DIM)},
        @"@model_path/weights/w1.bin":   @{@"offset":@0, @"data":build_blob(w->W1, HIDDEN, DIM)},
        @"@model_path/weights/w3.bin":   @{@"offset":@0, @"data":build_blob(w->W3, HIDDEN, DIM)},
        @"@model_path/weights/w2.bin":   @{@"offset":@0, @"data":build_blob(w->W2, DIM, HIDDEN)},
    }), DIM*SEQ*2, (2*DIM + 3*HIDDEN)*SEQ*2);

    lk->ffnBwd = compile_kern(gen_ffn_bwd(), (@{
        @"@model_path/weights/w2t.bin": @{@"offset":@0, @"data":build_blob_t(w->W2, DIM, HIDDEN)},
        @"@model_path/weights/w1t.bin": @{@"offset":@0, @"data":build_blob_t(w->W1, HIDDEN, DIM)},
        @"@model_path/weights/w3t.bin": @{@"offset":@0, @"data":build_blob_t(w->W3, HIDDEN, DIM)},
    }), (DIM + 2*HIDDEN)*SEQ*2, (DIM + 2*HIDDEN)*SEQ*2);

    lk->sdpaBwd1 = compile_kern(gen_sdpa_bwd1(), (@{
        @"@model_path/weights/mask.bin": @{@"offset":@0, @"data":get_mask_blob()},
        @"@model_path/weights/wot.bin":  @{@"offset":@0, @"data":build_blob_t(w->Wo, DIM, DIM)},
    }), 4*DIM*SEQ*2, (DIM + 2*SCORE_CH)*SEQ*2);

    lk->qkvBwd = compile_kern(gen_qkvb(), (@{
        @"@model_path/weights/wqt.bin": @{@"offset":@0, @"data":build_blob_t(w->Wq, DIM, DIM)},
        @"@model_path/weights/wkt.bin": @{@"offset":@0, @"data":build_blob_t(w->Wk, DIM, DIM)},
        @"@model_path/weights/wvt.bin": @{@"offset":@0, @"data":build_blob_t(w->Wv, DIM, DIM)},
    }), 3*DIM*SEQ*2, DIM*SEQ*2);

    *compile_count += KERNELS_PER_LAYER;
    return lk->fwdAttn && lk->fwdFFN && lk->ffnBwd && lk->sdpaBwd1 && lk->qkvBwd;
}

static Kern *compile_sdpa_bwd2_kern(int *compile_count) {
    Kern *k = compile_kern(gen_sdpa_bwd2(), @{},
        (2*SCORE_CH + 2*DIM)*SEQ*2, 2*DIM*SEQ*2);
    if (k) (*compile_count)++;
    return k;
}

static void free_layer_kernels(LayerKernels *lk) {
    free_kern(lk->fwdAttn); free_kern(lk->fwdFFN); free_kern(lk->ffnBwd);
    free_kern(lk->sdpaBwd1); free_kern(lk->qkvBwd);
    lk->fwdAttn = lk->fwdFFN = lk->ffnBwd = lk->sdpaBwd1 = lk->qkvBwd = NULL;
}

// ===== Weight loading from llama2.c format =====
static bool load_pretrained(LayerWeights *lw, float *rms_final, float *embed, const char *path) {
    FILE *f = fopen(path, "rb");
    if (!f) return false;
    Llama2Config cfg;
    fread(&cfg, sizeof(cfg), 1, f);
    if (cfg.dim != DIM || cfg.hidden_dim != HIDDEN || cfg.n_layers != NLAYERS) {
        fclose(f); return false;
    }
    int V = abs(cfg.vocab_size);
    fread(embed, 4, V * DIM, f);
    for (int L = 0; L < NLAYERS; L++) fread(lw[L].rms_att, 4, DIM, f);
    for (int L = 0; L < NLAYERS; L++) fread(lw[L].Wq, 4, WQ_SZ, f);
    for (int L = 0; L < NLAYERS; L++) fread(lw[L].Wk, 4, WQ_SZ, f);
    for (int L = 0; L < NLAYERS; L++) fread(lw[L].Wv, 4, WQ_SZ, f);
    for (int L = 0; L < NLAYERS; L++) fread(lw[L].Wo, 4, WO_SZ, f);
    for (int L = 0; L < NLAYERS; L++) fread(lw[L].rms_ffn, 4, DIM, f);
    for (int L = 0; L < NLAYERS; L++) fread(lw[L].W1, 4, W1_SZ, f);
    for (int L = 0; L < NLAYERS; L++) fread(lw[L].W2, 4, W2_SZ, f);
    for (int L = 0; L < NLAYERS; L++) fread(lw[L].W3, 4, W3_SZ, f);
    fread(rms_final, 4, DIM, f);
    fclose(f);
    return true;
}

// ===== Random init (same as macOS lines 253-269) =====
static void random_init_weights(LayerWeights *lw, float *rms_final, float *embed) {
    srand48(42);
    float scale_d = 1.0f / sqrtf(DIM), scale_h = 1.0f / sqrtf(HIDDEN);
    float out_scale = 1.0f / sqrtf((float)NLAYERS);
    for (int L = 0; L < NLAYERS; L++) {
        for (size_t i = 0; i < WQ_SZ; i++) {
            lw[L].Wq[i] = scale_d * (2*drand48()-1);
            lw[L].Wk[i] = scale_d * (2*drand48()-1);
        }
        for (size_t i = 0; i < WQ_SZ; i++) {
            lw[L].Wv[i] = scale_d * (2*drand48()-1);
            lw[L].Wo[i] = scale_d * out_scale * (2*drand48()-1);
        }
        for (size_t i = 0; i < W1_SZ; i++) lw[L].W1[i] = scale_h * (2*drand48()-1);
        for (size_t i = 0; i < W2_SZ; i++) lw[L].W2[i] = scale_d * out_scale * (2*drand48()-1);
        for (size_t i = 0; i < W3_SZ; i++) lw[L].W3[i] = scale_h * (2*drand48()-1);
        for (int i = 0; i < DIM; i++) { lw[L].rms_att[i] = 1.0f; lw[L].rms_ffn[i] = 1.0f; }
    }
    for (int i = 0; i < DIM; i++) rms_final[i] = 1.0f;
    float escale = 0.02f;
    for (size_t i = 0; i < (size_t)VOCAB * DIM; i++) embed[i] = escale * (2*drand48()-1);
}

// ===== Compile all kernels =====
static bool compile_all_kernels(ANETrainState *s) {
    s->compiling = true;

    // Free existing weight-bearing kernels
    for (int L = 0; L < NLAYERS; L++) free_layer_kernels(&s->kern[L]);

    // Compile weight-bearing kernels for all layers
    for (int L = 0; L < NLAYERS; L++) {
        if (!compile_layer_kernels(&s->kern[L], &s->lw[L], &s->compile_count)) {
            fprintf(stderr, "[engine] Compile failed at layer %d\n", L);
            s->compiling = false;
            return false;
        }
    }

    // Re-compile sdpaBwd2 if needed (weight-free, one per layer)
    for (int L = 0; L < NLAYERS; L++) {
        if (!s->sdpaBwd2[L]) {
            s->sdpaBwd2[L] = compile_sdpa_bwd2_kern(&s->compile_count);
            if (!s->sdpaBwd2[L]) {
                fprintf(stderr, "[engine] sdpaBwd2 compile failed at layer %d\n", L);
                s->compiling = false;
                return false;
            }
        }
    }

    s->kernels_compiled = true;
    s->compiling = false;
    return true;
}

// ===== iOS compile budget reset (no exec()) =====
static bool check_and_reset_compile_budget(ANETrainState *s) {
    if (s->compile_count + TOTAL_WEIGHT_KERNELS + NLAYERS <= IOS_MAX_COMPILES) return true;

    // Budget exhausted: free all kernels, reset counter, recompile
    fprintf(stderr, "[engine] Compile budget reached (%d), resetting...\n", s->compile_count);
    for (int L = 0; L < NLAYERS; L++) {
        free_layer_kernels(&s->kern[L]);
        free_kern(s->sdpaBwd2[L]);
        s->sdpaBwd2[L] = NULL;
    }
    s->compile_count = 0;
    s->kernels_compiled = false;
    return compile_all_kernels(s);
}

// ===== Public API: ane_train_init =====
ANETrainState *ane_train_init(const char *model_path, const char *data_path) {
    @autoreleasepool {
    ane_init();

    ANETrainState *s = (ANETrainState *)calloc(1, sizeof(ANETrainState));
    s->lr = 3e-4f;
    s->total_steps = 10000;
    s->last_loss = 999.0f;

    // Allocate per-layer state
    for (int L = 0; L < NLAYERS; L++) {
        s->lw[L] = layer_weights_alloc();
        s->la[L] = layer_adam_alloc();
        s->acts[L] = layer_acts_alloc();
        s->grads[L] = layer_grads_alloc();
        memset(&s->kern[L], 0, sizeof(LayerKernels));
        s->sdpaBwd2[L] = NULL;
    }

    // Global weights + optimizer
    s->rms_final = (float *)malloc(DIM * 4);
    s->embed = (float *)malloc(VOCAB * DIM * 4);
    s->grms_final = (float *)calloc(DIM, 4);
    s->gembed = (float *)calloc(VOCAB * DIM, 4);
    s->arms_final = adam_alloc(DIM);
    s->aembed = adam_alloc((size_t)VOCAB * DIM);

    // Scratch buffers
    s->x_cur     = (float *)malloc(SEQ * DIM * 4);
    s->x_final   = (float *)malloc(SEQ * DIM * 4);
    s->logits    = (float *)malloc(SEQ * VOCAB * 4);
    s->dlogits   = (float *)malloc(SEQ * VOCAB * 4);
    s->dy        = (float *)malloc(SEQ * DIM * 4);
    s->dffn      = (float *)malloc(SEQ * DIM * 4);
    s->dh1       = (float *)malloc(SEQ * HIDDEN * 4);
    s->dh3       = (float *)malloc(SEQ * HIDDEN * 4);
    s->dx_ffn    = (float *)malloc(SEQ * DIM * 4);
    s->dx2       = (float *)malloc(SEQ * DIM * 4);
    s->do_out_buf= (float *)malloc(SEQ * DIM * 4);
    s->dq        = (float *)malloc(SEQ * DIM * 4);
    s->dk        = (float *)malloc(SEQ * DIM * 4);
    s->dv        = (float *)malloc(SEQ * DIM * 4);
    s->dx_attn   = (float *)malloc(SEQ * DIM * 4);

    // Load weights: pretrained or random
    bool loaded = false;
    if (model_path) {
        loaded = load_pretrained(s->lw, s->rms_final, s->embed, model_path);
    }
    if (!loaded) {
        random_init_weights(s->lw, s->rms_final, s->embed);
    }

    // mmap token data
    s->data_fd = -1;
    s->token_data = NULL;
    s->n_tokens = 0;
    if (data_path) {
        s->data_fd = open(data_path, O_RDONLY);
        if (s->data_fd >= 0) {
            struct stat st;
            fstat(s->data_fd, &st);
            s->data_len = st.st_size;
            s->token_data = (uint16_t *)mmap(NULL, s->data_len, PROT_READ, MAP_PRIVATE, s->data_fd, 0);
            if (s->token_data == MAP_FAILED) {
                s->token_data = NULL;
                close(s->data_fd);
                s->data_fd = -1;
            } else {
                s->n_tokens = s->data_len / 2;
            }
        }
    }

    // Concurrency
    s->dw_q = dispatch_queue_create("ane.train.dw_cblas", DISPATCH_QUEUE_SERIAL);
    s->dw_grp = dispatch_group_create();

    // Compile initial kernels
    // sdpaBwd2 first (weight-free, one per layer)
    for (int L = 0; L < NLAYERS; L++) {
        s->sdpaBwd2[L] = compile_sdpa_bwd2_kern(&s->compile_count);
    }
    compile_all_kernels(s);

    // Zero gradient accumulators for first batch
    for (int L = 0; L < NLAYERS; L++) layer_grads_zero(&s->grads[L]);
    memset(s->grms_final, 0, DIM * 4);
    memset(s->gembed, 0, (size_t)VOCAB * DIM * 4);

    return s;
    }
}

// ===== Public API: ane_train_step =====
// Ported from train_large.m lines 396-654
float ane_train_step(ANETrainState *s) {
    @autoreleasepool {

    // Check compile budget, reset if needed (iOS: no exec())
    if (!s->kernels_compiled) {
        if (!check_and_reset_compile_budget(s)) return -1.0f;
    }

    // Sample random position in token data
    size_t max_pos = s->n_tokens - SEQ - 1;
    size_t pos = (size_t)(drand48() * max_pos);
    uint16_t *input_tokens = s->token_data + pos;
    uint16_t *target_tokens = s->token_data + pos + 1;

    // Embedding lookup -> x_cur [DIM, SEQ] channel-first
    embed_lookup(s->x_cur, s->embed, input_tokens, DIM, SEQ);

    // ===== FORWARD (12 layers) =====
    for (int L = 0; L < NLAYERS; L++) {
        LayerActs *ac = &s->acts[L];

        // Save layer input for rmsnorm1 backward
        memcpy(ac->layer_in, s->x_cur, SEQ * DIM * 4);

        // Wait for any pending dW from previous step's backward
        dispatch_group_wait(s->dw_grp, DISPATCH_TIME_FOREVER);

        // --- Attention forward: x_cur -> o_out,Q,K,V,attn_out,xnorm ---
        io_write_fp16(s->kern[L].fwdAttn->ioIn, s->x_cur, DIM, SEQ);
        ane_eval(s->kern[L].fwdAttn);

        // Read taps from fwdAttn output: [o_out(0), Q(DIM), K(2*DIM), V(3*DIM), attn_out(4*DIM), xnorm(5*DIM)]
        io_read_fp16(s->kern[L].fwdAttn->ioOut, ac->o_out,    0,       DIM, SEQ);
        io_read_fp16(s->kern[L].fwdAttn->ioOut, ac->attn_out, 4*DIM,   DIM, SEQ);
        io_read_fp16(s->kern[L].fwdAttn->ioOut, ac->xnorm,    5*DIM,   DIM, SEQ);

        // x2 = x_cur + o_out (residual)
        vDSP_vadd(s->x_cur, 1, ac->o_out, 1, ac->x2, 1, (vDSP_Length)(SEQ * DIM));

        // --- FFN forward: x2 -> ffn_out,h1,h3,silu_out,x2norm ---
        io_write_fp16(s->kern[L].fwdFFN->ioIn, ac->x2, DIM, SEQ);
        ane_eval(s->kern[L].fwdFFN);

        // Read taps: [ffn_out(0), h1(DIM), h3(DIM+HIDDEN), silu_out(DIM+2*HIDDEN), x2norm(DIM+3*HIDDEN)]
        io_read_fp16(s->kern[L].fwdFFN->ioOut, ac->ffn_out,  0,              DIM,    SEQ);
        io_read_fp16(s->kern[L].fwdFFN->ioOut, ac->h1,       DIM,            HIDDEN, SEQ);
        io_read_fp16(s->kern[L].fwdFFN->ioOut, ac->h3,       DIM + HIDDEN,   HIDDEN, SEQ);
        io_read_fp16(s->kern[L].fwdFFN->ioOut, ac->silu_out, DIM + 2*HIDDEN, HIDDEN, SEQ);
        io_read_fp16(s->kern[L].fwdFFN->ioOut, ac->x2norm,   DIM + 3*HIDDEN, DIM,    SEQ);

        // x_cur = x2 + ffn_out (residual)
        vDSP_vadd(ac->x2, 1, ac->ffn_out, 1, s->x_cur, 1, (vDSP_Length)(SEQ * DIM));
    }

    // Final RMSNorm (CPU)
    rmsnorm(s->x_final, s->x_cur, s->rms_final, DIM, SEQ);

    // Classifier: logits = embed @ x_final  (embed[VOCAB,DIM] @ x_final[DIM,SEQ] = logits[VOCAB,SEQ])
    cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans,
                VOCAB, SEQ, DIM, 1.0f,
                s->embed, DIM, s->x_final, SEQ, 0.0f, s->logits, SEQ);

    // Cross-entropy loss + dlogits
    float loss = cross_entropy_loss(s->dlogits, s->logits, target_tokens, VOCAB, SEQ);
    s->last_loss = loss;

    // ===== BACKWARD =====

    // Classifier backward: dy = embed^T @ dlogits
    cblas_sgemm(CblasRowMajor, CblasTrans, CblasNoTrans,
                DIM, SEQ, VOCAB, 1.0f,
                s->embed, DIM, s->dlogits, SEQ, 0.0f, s->dy, SEQ);

    // dembed += dlogits @ x_final^T (async)
    // Capture pointers for block
    float *capt_dlogits = (float *)malloc(SEQ * VOCAB * 4);
    memcpy(capt_dlogits, s->dlogits, SEQ * VOCAB * 4);
    float *capt_xf = (float *)malloc(SEQ * DIM * 4);
    memcpy(capt_xf, s->x_final, SEQ * DIM * 4);
    float *gembed_ptr = s->gembed;
    dispatch_group_async(s->dw_grp, s->dw_q, ^{
        cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasTrans,
                    VOCAB, DIM, SEQ, 1.0f,
                    capt_dlogits, SEQ, capt_xf, SEQ, 1.0f, gembed_ptr, DIM);
        free(capt_dlogits);
        free(capt_xf);
    });

    // Final RMSNorm backward (CPU)
    float *dx_rms_final = (float *)calloc(SEQ * DIM, 4);
    rmsnorm_bwd(dx_rms_final, s->grms_final, s->dy, s->x_cur, s->rms_final, DIM, SEQ);
    memcpy(s->dy, dx_rms_final, SEQ * DIM * 4);
    free(dx_rms_final);

    // ===== BACKWARD (12 layers, reverse) =====
    for (int L = NLAYERS - 1; L >= 0; L--) {
        LayerActs *ac = &s->acts[L];
        LayerGrads *gr = &s->grads[L];

        // dffn = dy (residual: d(x2 + ffn) = dy for both paths)
        memcpy(s->dffn, s->dy, SEQ * DIM * 4);

        // --- FFN backward (ANE) ---
        // Input: concat(dffn, h1, h3) -> output: concat(dx_ffn, dh1, dh3)
        io_write_fp16_at(s->kern[L].ffnBwd->ioIn, 0, s->dffn, DIM, SEQ);
        io_copy(s->kern[L].ffnBwd->ioIn, DIM, s->kern[L].fwdFFN->ioOut, DIM, 2*HIDDEN, SEQ);
        ane_eval(s->kern[L].ffnBwd);
        io_read_fp16(s->kern[L].ffnBwd->ioOut, s->dx_ffn, 0,            DIM,    SEQ);
        io_read_fp16(s->kern[L].ffnBwd->ioOut, s->dh1,    DIM,          HIDDEN, SEQ);
        io_read_fp16(s->kern[L].ffnBwd->ioOut, s->dh3,    DIM + HIDDEN, HIDDEN, SEQ);

        // dW FFN async (cblas on serial queue)
        float *capt_dffn_b = (float *)malloc(SEQ * DIM * 4);     memcpy(capt_dffn_b, s->dffn, SEQ * DIM * 4);
        float *capt_silu   = (float *)malloc(SEQ * HIDDEN * 4);  memcpy(capt_silu, ac->silu_out, SEQ * HIDDEN * 4);
        float *capt_dh1_b  = (float *)malloc(SEQ * HIDDEN * 4);  memcpy(capt_dh1_b, s->dh1, SEQ * HIDDEN * 4);
        float *capt_dh3_b  = (float *)malloc(SEQ * HIDDEN * 4);  memcpy(capt_dh3_b, s->dh3, SEQ * HIDDEN * 4);
        float *capt_x2n    = (float *)malloc(SEQ * DIM * 4);     memcpy(capt_x2n, ac->x2norm, SEQ * DIM * 4);
        float *grW2 = gr->W2, *grW1 = gr->W1, *grW3 = gr->W3;
        dispatch_group_async(s->dw_grp, s->dw_q, ^{
            // dW2 += dffn @ silu_out^T  [DIM,HIDDEN]
            cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasTrans, DIM, HIDDEN, SEQ,
                        1.0f, capt_dffn_b, SEQ, capt_silu, SEQ, 1.0f, grW2, HIDDEN);
            // dW1 += dh1 @ x2norm^T  [HIDDEN,DIM]
            cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasTrans, HIDDEN, DIM, SEQ,
                        1.0f, capt_dh1_b, SEQ, capt_x2n, SEQ, 1.0f, grW1, DIM);
            // dW3 += dh3 @ x2norm^T  [HIDDEN,DIM]
            cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasTrans, HIDDEN, DIM, SEQ,
                        1.0f, capt_dh3_b, SEQ, capt_x2n, SEQ, 1.0f, grW3, DIM);
            free(capt_dffn_b); free(capt_silu); free(capt_dh1_b); free(capt_dh3_b); free(capt_x2n);
        });

        // RMSNorm2 backward (CPU)
        memset(s->dx2, 0, SEQ * DIM * 4);
        rmsnorm_bwd(s->dx2, gr->rms_ffn, s->dx_ffn, ac->x2, s->lw[L].rms_ffn, DIM, SEQ);
        // Add residual: dx2 += dy
        for (int i = 0; i < SEQ * DIM; i++) s->dx2[i] += s->dy[i];

        // dWo async
        float *capt_do = (float *)malloc(SEQ * DIM * 4); memcpy(capt_do, s->dx2, SEQ * DIM * 4);
        float *capt_attn = (float *)malloc(SEQ * DIM * 4); memcpy(capt_attn, ac->attn_out, SEQ * DIM * 4);
        float *grWo = gr->Wo;
        dispatch_group_async(s->dw_grp, s->dw_q, ^{
            cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasTrans, DIM, DIM, SEQ,
                        1.0f, capt_do, SEQ, capt_attn, SEQ, 1.0f, grWo, DIM);
            free(capt_do); free(capt_attn);
        });

        // --- SDPA backward part 1 (ANE) ---
        // Input: concat(Q, K, V, dx2)  from fwdAttn->ioOut offsets + dx2
        io_copy(s->kern[L].sdpaBwd1->ioIn, 0, s->kern[L].fwdAttn->ioOut, DIM, 3*DIM, SEQ);
        io_write_fp16_at(s->kern[L].sdpaBwd1->ioIn, 3*DIM, s->dx2, DIM, SEQ);
        ane_eval(s->kern[L].sdpaBwd1);

        // --- SDPA backward part 2 (ANE, weight-free) ---
        // Input: concat(probs, dp, Q, K) from sdpaBwd1->ioOut + fwdAttn->ioOut
        io_copy(s->sdpaBwd2[L]->ioIn, 0, s->kern[L].sdpaBwd1->ioOut, DIM, 2*SCORE_CH, SEQ);
        io_copy(s->sdpaBwd2[L]->ioIn, 2*SCORE_CH, s->kern[L].fwdAttn->ioOut, DIM, 2*DIM, SEQ);
        ane_eval(s->sdpaBwd2[L]);

        // Read dQ, dK from sdpaBwd2; dV from sdpaBwd1
        io_read_fp16(s->sdpaBwd2[L]->ioOut, s->dq, 0,   DIM, SEQ);
        io_read_fp16(s->sdpaBwd2[L]->ioOut, s->dk, DIM,  DIM, SEQ);
        io_read_fp16(s->kern[L].sdpaBwd1->ioOut, s->dv, 0, DIM, SEQ);

        // dWq/dWk/dWv async
        float *capt_dq_b = (float *)malloc(SEQ * DIM * 4); memcpy(capt_dq_b, s->dq, SEQ * DIM * 4);
        float *capt_dk_b = (float *)malloc(SEQ * DIM * 4); memcpy(capt_dk_b, s->dk, SEQ * DIM * 4);
        float *capt_dv_b = (float *)malloc(SEQ * DIM * 4); memcpy(capt_dv_b, s->dv, SEQ * DIM * 4);
        float *capt_xn   = (float *)malloc(SEQ * DIM * 4); memcpy(capt_xn, ac->xnorm, SEQ * DIM * 4);
        float *grWq = gr->Wq, *grWk = gr->Wk, *grWv = gr->Wv;
        dispatch_group_async(s->dw_grp, s->dw_q, ^{
            cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasTrans, DIM, DIM, SEQ,
                        1.0f, capt_dq_b, SEQ, capt_xn, SEQ, 1.0f, grWq, DIM);
            cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasTrans, DIM, DIM, SEQ,
                        1.0f, capt_dk_b, SEQ, capt_xn, SEQ, 1.0f, grWk, DIM);
            cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasTrans, DIM, DIM, SEQ,
                        1.0f, capt_dv_b, SEQ, capt_xn, SEQ, 1.0f, grWv, DIM);
            free(capt_dq_b); free(capt_dk_b); free(capt_dv_b); free(capt_xn);
        });

        // --- QKV backward (ANE) ---
        // Input: concat(dQ, dK, dV)  -> output: dx_attn
        io_copy(s->kern[L].qkvBwd->ioIn, 0, s->sdpaBwd2[L]->ioOut, 0, 2*DIM, SEQ);
        io_copy(s->kern[L].qkvBwd->ioIn, 2*DIM, s->kern[L].sdpaBwd1->ioOut, 0, DIM, SEQ);
        ane_eval(s->kern[L].qkvBwd);
        io_read_fp16(s->kern[L].qkvBwd->ioOut, s->dx_attn, 0, DIM, SEQ);

        // RMSNorm1 backward (CPU)
        float *dx_rms1 = (float *)calloc(SEQ * DIM, 4);
        rmsnorm_bwd(dx_rms1, gr->rms_att, s->dx_attn, ac->layer_in, s->lw[L].rms_att, DIM, SEQ);

        // dy for next layer backward = dx_rms1 + dx2 (skip connection)
        for (int i = 0; i < SEQ * DIM; i++) s->dy[i] = dx_rms1[i] + s->dx2[i];
        free(dx_rms1);
    }

    // Embedding backward
    dispatch_group_wait(s->dw_grp, DISPATCH_TIME_FOREVER);
    embed_backward(s->gembed, s->dy, input_tokens, DIM, SEQ);

    s->accum_count++;
    s->step++;

    // ===== Adam update when accumulation batch is complete =====
    if (s->accum_count >= IOS_ACCUM_STEPS) {
        dispatch_group_wait(s->dw_grp, DISPATCH_TIME_FOREVER);

        float gsc = 1.0f / s->accum_count;
        s->adam_t++;

        float adam_b1 = 0.9f, adam_b2 = 0.999f, adam_eps = 1e-8f;

        for (int L = 0; L < NLAYERS; L++) {
            LayerGrads *g = &s->grads[L];
            // Scale gradients
            for (size_t i = 0; i < WQ_SZ; i++) { g->Wq[i] *= gsc; g->Wk[i] *= gsc; g->Wv[i] *= gsc; g->Wo[i] *= gsc; }
            for (size_t i = 0; i < W1_SZ; i++) g->W1[i] *= gsc;
            for (size_t i = 0; i < W2_SZ; i++) g->W2[i] *= gsc;
            for (size_t i = 0; i < W3_SZ; i++) g->W3[i] *= gsc;
            for (int i = 0; i < DIM; i++) { g->rms_att[i] *= gsc; g->rms_ffn[i] *= gsc; }

            // Adam update
            adam_update(s->lw[L].Wq, g->Wq, &s->la[L].Wq, s->adam_t, s->lr, adam_b1, adam_b2, adam_eps);
            adam_update(s->lw[L].Wk, g->Wk, &s->la[L].Wk, s->adam_t, s->lr, adam_b1, adam_b2, adam_eps);
            adam_update(s->lw[L].Wv, g->Wv, &s->la[L].Wv, s->adam_t, s->lr, adam_b1, adam_b2, adam_eps);
            adam_update(s->lw[L].Wo, g->Wo, &s->la[L].Wo, s->adam_t, s->lr, adam_b1, adam_b2, adam_eps);
            adam_update(s->lw[L].W1, g->W1, &s->la[L].W1, s->adam_t, s->lr, adam_b1, adam_b2, adam_eps);
            adam_update(s->lw[L].W2, g->W2, &s->la[L].W2, s->adam_t, s->lr, adam_b1, adam_b2, adam_eps);
            adam_update(s->lw[L].W3, g->W3, &s->la[L].W3, s->adam_t, s->lr, adam_b1, adam_b2, adam_eps);
            adam_update(s->lw[L].rms_att, g->rms_att, &s->la[L].rms_att, s->adam_t, s->lr, adam_b1, adam_b2, adam_eps);
            adam_update(s->lw[L].rms_ffn, g->rms_ffn, &s->la[L].rms_ffn, s->adam_t, s->lr, adam_b1, adam_b2, adam_eps);
        }

        // Final rmsnorm + embed
        for (int i = 0; i < DIM; i++) s->grms_final[i] *= gsc;
        adam_update(s->rms_final, s->grms_final, &s->arms_final, s->adam_t, s->lr, adam_b1, adam_b2, adam_eps);
        for (size_t i = 0; i < (size_t)VOCAB * DIM; i++) s->gembed[i] *= gsc;
        adam_update(s->embed, s->gembed, &s->aembed, s->adam_t, s->lr, adam_b1, adam_b2, adam_eps);

        // Reset accumulators
        s->accum_count = 0;
        for (int L = 0; L < NLAYERS; L++) layer_grads_zero(&s->grads[L]);
        memset(s->grms_final, 0, DIM * 4);
        memset(s->gembed, 0, (size_t)VOCAB * DIM * 4);

        // Weights changed -> must recompile kernels
        s->kernels_compiled = false;
        if (!check_and_reset_compile_budget(s)) {
            fprintf(stderr, "[engine] Recompile after Adam failed\n");
        }
    }

    return loss;
    }
}

// ===== Public API: accessors =====
int ane_train_current_step(ANETrainState *s)  { return s->step; }
float ane_train_current_loss(ANETrainState *s) { return s->last_loss; }
bool ane_train_is_compiling(ANETrainState *s)  { return s->compiling; }

// ===== Public API: save checkpoint =====
void ane_train_save(ANETrainState *s) {
    @autoreleasepool {
    NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
    NSString *docs = paths.firstObject;
    NSString *ckptPath = [docs stringByAppendingPathComponent:@"ane_stories110M_ckpt.bin"];
    const char *path = [ckptPath UTF8String];

    FILE *f = fopen(path, "wb");
    if (!f) { fprintf(stderr, "[save] Cannot open %s\n", path); return; }

    CkptHdr h = {0};
    h.magic = 0x424C5A54; h.version = 2;
    h.step = s->step; h.total_steps = s->total_steps;
    h.n_layers = NLAYERS; h.vocab_size = VOCAB; h.dim = DIM;
    h.hidden_dim = HIDDEN; h.n_heads = HEADS; h.seq_len = SEQ;
    h.lr = s->lr; h.loss = s->last_loss; h.adam_t = s->adam_t;
    fwrite(&h, sizeof(h), 1, f);

    for (int L = 0; L < NLAYERS; L++) {
        fwrite(s->lw[L].Wq, 4, WQ_SZ, f); fwrite(s->lw[L].Wk, 4, WQ_SZ, f);
        fwrite(s->lw[L].Wv, 4, WQ_SZ, f); fwrite(s->lw[L].Wo, 4, WO_SZ, f);
        fwrite(s->lw[L].W1, 4, W1_SZ, f); fwrite(s->lw[L].W2, 4, W2_SZ, f); fwrite(s->lw[L].W3, 4, W3_SZ, f);
        fwrite(s->lw[L].rms_att, 4, DIM, f); fwrite(s->lw[L].rms_ffn, 4, DIM, f);
        // Adam state
        fwrite(s->la[L].Wq.m, 4, WQ_SZ, f); fwrite(s->la[L].Wq.v, 4, WQ_SZ, f);
        fwrite(s->la[L].Wk.m, 4, WQ_SZ, f); fwrite(s->la[L].Wk.v, 4, WQ_SZ, f);
        fwrite(s->la[L].Wv.m, 4, WQ_SZ, f); fwrite(s->la[L].Wv.v, 4, WQ_SZ, f);
        fwrite(s->la[L].Wo.m, 4, WO_SZ, f); fwrite(s->la[L].Wo.v, 4, WO_SZ, f);
        fwrite(s->la[L].W1.m, 4, W1_SZ, f); fwrite(s->la[L].W1.v, 4, W1_SZ, f);
        fwrite(s->la[L].W2.m, 4, W2_SZ, f); fwrite(s->la[L].W2.v, 4, W2_SZ, f);
        fwrite(s->la[L].W3.m, 4, W3_SZ, f); fwrite(s->la[L].W3.v, 4, W3_SZ, f);
        fwrite(s->la[L].rms_att.m, 4, DIM, f); fwrite(s->la[L].rms_att.v, 4, DIM, f);
        fwrite(s->la[L].rms_ffn.m, 4, DIM, f); fwrite(s->la[L].rms_ffn.v, 4, DIM, f);
    }
    fwrite(s->rms_final, 4, DIM, f);
    fwrite(s->arms_final.m, 4, DIM, f); fwrite(s->arms_final.v, 4, DIM, f);
    fwrite(s->embed, 4, VOCAB * DIM, f);
    fwrite(s->aembed.m, 4, VOCAB * DIM, f); fwrite(s->aembed.v, 4, VOCAB * DIM, f);
    fclose(f);
    fprintf(stderr, "[save] Checkpoint saved to %s (step %d, loss %.4f)\n", path, s->step, s->last_loss);
    }
}

// ===== Public API: free =====
void ane_train_free(ANETrainState *s) {
    if (!s) return;

    dispatch_group_wait(s->dw_grp, DISPATCH_TIME_FOREVER);

    for (int L = 0; L < NLAYERS; L++) {
        free_layer_kernels(&s->kern[L]);
        free_kern(s->sdpaBwd2[L]);
        layer_weights_free(&s->lw[L]);
        layer_adam_free(&s->la[L]);
        layer_acts_free(&s->acts[L]);
        layer_grads_free(&s->grads[L]);
    }

    free(s->rms_final); free(s->embed);
    free(s->grms_final); free(s->gembed);
    adam_free(&s->arms_final);
    adam_free(&s->aembed);

    free(s->x_cur); free(s->x_final);
    free(s->logits); free(s->dlogits);
    free(s->dy); free(s->dffn);
    free(s->dh1); free(s->dh3);
    free(s->dx_ffn); free(s->dx2);
    free(s->do_out_buf);
    free(s->dq); free(s->dk); free(s->dv);
    free(s->dx_attn);

    if (s->token_data && s->data_len > 0) {
        munmap(s->token_data, s->data_len);
    }
    if (s->data_fd >= 0) close(s->data_fd);

    free(s);
}

// ===== Quick test =====
NSString *ane_training_engine_test(void) {
    @autoreleasepool {
    NSMutableString *log = [NSMutableString string];
    [log appendString:@"=== ANE Training Engine Test ===\n"];

    // Create dummy token data file in tmp
    NSString *tmpPath = [NSTemporaryDirectory() stringByAppendingPathComponent:@"ane_test_tokens.bin"];
    {
        size_t n = 10000;
        uint16_t *buf = (uint16_t *)malloc(n * 2);
        srand48(123);
        for (size_t i = 0; i < n; i++) buf[i] = (uint16_t)(drand48() * (VOCAB - 1));
        NSData *d = [NSData dataWithBytesNoCopy:buf length:n * 2 freeWhenDone:YES];
        [d writeToFile:tmpPath atomically:YES];
    }

    [log appendString:@"Init with random weights...\n"];
    ANETrainState *s = ane_train_init(NULL, [tmpPath UTF8String]);
    if (!s) {
        [log appendString:@"FAIL: ane_train_init returned NULL\n"];
        return log;
    }
    if (!s->kernels_compiled) {
        [log appendString:@"FAIL: kernels not compiled\n"];
        ane_train_free(s);
        return log;
    }
    [log appendFormat:@"Init OK. Compile count: %d\n", s->compile_count];

    // Run 20 steps (enough for 5 Adam updates with ACCUM_STEPS=4)
    int nsteps = 20;
    float first_loss = 0, last_loss = 0;
    for (int i = 0; i < nsteps; i++) {
        float loss = ane_train_step(s);
        if (i == 0) first_loss = loss;
        last_loss = loss;
        if (i < 8 || i == nsteps-1 || (i+1) % 4 == 0)
            [log appendFormat:@"Step %d: loss=%.4f%s\n", i, loss,
                (i+1) % IOS_ACCUM_STEPS == 0 ? @" [Adam update + recompile]" : @""];
        if (loss < 0) {
            [log appendFormat:@"FAIL: negative loss at step %d\n", i];
            ane_train_free(s);
            return log;
        }
    }

    // Check loss trend
    [log appendFormat:@"\nFirst loss: %.4f (expected ~%.2f for random init)\n", first_loss, logf(VOCAB)];
    bool trend_ok = last_loss < first_loss;
    [log appendFormat:@"Loss trend: %.4f -> %.4f (%s)\n",
        first_loss, last_loss, trend_ok ? "DECREASING - OK" : "NOT DECREASING - may need more steps"];

    [log appendFormat:@"\nFinal state: step=%d adam_t=%d\n", ane_train_current_step(s), s->adam_t];

    ane_train_free(s);
    [[NSFileManager defaultManager] removeItemAtPath:tmpPath error:nil];

    [log appendString:@"\n=== Test Complete ===\n"];
    return log;
    }
}

// ===== Overnight training: long run with real data =====
NSString *ane_overnight_training(int max_steps) {
    @autoreleasepool {
    NSMutableString *log = [NSMutableString string];
    [log appendString:@"=== ANE Overnight Training ===\n"];

    // Try to find bundled training data
    NSString *dataPath = [[NSBundle mainBundle] pathForResource:@"tinystories_data00" ofType:@"bin"];
    if (!dataPath) {
        // Fall back to dummy data
        [log appendString:@"No bundled training data, using random tokens\n"];
        NSString *tmpPath = [NSTemporaryDirectory() stringByAppendingPathComponent:@"ane_overnight_tokens.bin"];
        size_t n = 100000; // 100K tokens
        uint16_t *buf = (uint16_t *)malloc(n * 2);
        srand48(42);
        for (size_t i = 0; i < n; i++) buf[i] = (uint16_t)(drand48() * (VOCAB - 1));
        NSData *d = [NSData dataWithBytesNoCopy:buf length:n * 2 freeWhenDone:YES];
        [d writeToFile:tmpPath atomically:YES];
        dataPath = tmpPath;
    } else {
        [log appendFormat:@"Using bundled data: %@\n", [dataPath lastPathComponent]];
    }

    struct stat st;
    stat([dataPath UTF8String], &st);
    size_t n_tokens = st.st_size / 2;
    [log appendFormat:@"Tokens: %zu (%.1f KB)\n", n_tokens, st.st_size / 1024.0];
    [log appendFormat:@"Target: %d steps, ACCUM_STEPS=%d\n", max_steps, IOS_ACCUM_STEPS];

    // Init with random weights
    [log appendString:@"Initializing...\n"];
    uint64_t t_init = mach_absolute_time();
    ANETrainState *s = ane_train_init(NULL, [dataPath UTF8String]);
    if (!s) {
        [log appendString:@"FAIL: init returned NULL\n"];
        return log;
    }
    double init_ms = (double)(mach_absolute_time() - t_init) * g_tb.numer / g_tb.denom / 1e6;
    [log appendFormat:@"Init OK: %d kernels, %.1fs\n", s->compile_count, init_ms/1000];

    // Training loop with periodic logging
    float best_loss = 999.0f;
    float first_loss = 0;
    uint64_t t_start = mach_absolute_time();
    int log_interval = max_steps > 200 ? 50 : 10;
    int ckpt_interval = max_steps > 500 ? 100 : 50;

    // Log to file on device for persistence
    NSString *logPath = [NSString stringWithFormat:@"%@/ane_training_log.txt",
        [NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) firstObject]];
    FILE *logFile = fopen([logPath UTF8String], "w");
    if (logFile) fprintf(logFile, "step,loss,ms_step,adam_t,compile_count\n");

    for (int step = 0; step < max_steps; step++) {
        uint64_t t_step = mach_absolute_time();
        float loss = ane_train_step(s);
        double step_ms = (double)(mach_absolute_time() - t_step) * g_tb.numer / g_tb.denom / 1e6;

        if (step == 0) first_loss = loss;
        if (loss < best_loss) best_loss = loss;

        // Log to file
        if (logFile) {
            fprintf(logFile, "%d,%.6f,%.1f,%d,%d\n", step, loss, step_ms, s->adam_t, s->compile_count);
            if (step % 10 == 0) fflush(logFile);
        }

        // Log to console
        if (step < 10 || step % log_interval == 0 || step == max_steps - 1) {
            double elapsed_s = (double)(mach_absolute_time() - t_start) * g_tb.numer / g_tb.denom / 1e9;
            double steps_per_s = (step + 1) / elapsed_s;
            double eta_s = (max_steps - step - 1) / steps_per_s;
            [log appendFormat:@"step %-5d loss=%.4f best=%.4f ms/step=%.0f adam_t=%d steps/s=%.1f ETA=%.0fs\n",
                step, loss, best_loss, step_ms, s->adam_t, steps_per_s, eta_s];
            // Also print to stderr for console capture
            fprintf(stderr, "ANEPROBE: step %-5d loss=%.4f best=%.4f ms/step=%.0f adam_t=%d\n",
                step, loss, best_loss, step_ms, s->adam_t);
        }

        // Checkpoint
        if (step > 0 && step % ckpt_interval == 0) {
            fprintf(stderr, "ANEPROBE: [checkpoint at step %d]\n", step);
        }
    }

    if (logFile) fclose(logFile);

    double total_s = (double)(mach_absolute_time() - t_start) * g_tb.numer / g_tb.denom / 1e9;

    [log appendFormat:@"\n=== Training Complete ===\n"];
    [log appendFormat:@"Steps: %d in %.1fs (%.1f steps/s)\n", max_steps, total_s, max_steps/total_s];
    [log appendFormat:@"Loss: %.4f → %.4f (best: %.4f)\n", first_loss, ane_train_current_loss(s), best_loss];
    [log appendFormat:@"Adam updates: %d\n", s->adam_t];
    [log appendFormat:@"Compiles: %d\n", s->compile_count];
    [log appendFormat:@"Log saved to: %@\n", logPath];

    ane_train_free(s);
    return log;
    }
}

// ===== TIME-BASED training: runs for N hours, auto-iterates =====
NSString *ane_timed_training(float hours) {
    @autoreleasepool {
    NSMutableString *log = [NSMutableString string];
    [log appendFormat:@"=== ANE Timed Training (%.1f hours) ===\n", hours];

    // Find data
    NSString *dataPath = [[NSBundle mainBundle] pathForResource:@"tinystories_data00" ofType:@"bin"];
    if (!dataPath) {
        [log appendString:@"No bundled training data, creating dummy\n"];
        NSString *tmpPath = [NSTemporaryDirectory() stringByAppendingPathComponent:@"ane_timed_tokens.bin"];
        size_t n = 100000;
        uint16_t *buf = (uint16_t *)malloc(n * 2);
        srand48(42);
        for (size_t i = 0; i < n; i++) buf[i] = (uint16_t)(drand48() * (VOCAB - 1));
        NSData *d = [NSData dataWithBytesNoCopy:buf length:n * 2 freeWhenDone:YES];
        [d writeToFile:tmpPath atomically:YES];
        dataPath = tmpPath;
    } else {
        [log appendFormat:@"Data: %@\n", [dataPath lastPathComponent]];
    }

    // Init
    [log appendString:@"Initializing...\n"];
    fprintf(stderr, "ANEPROBE: Initializing timed training (%.1f hours)...\n", hours);
    ANETrainState *s = ane_train_init(NULL, [dataPath UTF8String]);
    if (!s) {
        [log appendString:@"FAIL: init returned NULL\n"];
        return log;
    }
    [log appendFormat:@"Init OK: %d kernels compiled\n", s->compile_count];
    fprintf(stderr, "ANEPROBE: Init OK, %d kernels. Starting training...\n", s->compile_count);

    // Log file
    NSString *docsDir = [NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) firstObject];
    NSString *logPath = [docsDir stringByAppendingPathComponent:@"ane_timed_training_log.csv"];
    FILE *logFile = fopen([logPath UTF8String], "w");
    if (logFile) fprintf(logFile, "step,loss,best_loss,lr,ms_step,adam_t,elapsed_min,phase\n");

    // Training parameters
    float lr = 3e-4f;
    float lr_min = 1e-5f;
    float best_loss = 999.0f;
    float phase_start_loss = 999.0f;
    int plateau_count = 0;
    int phase = 1;
    int phase_start_step = 0;
    int total_steps = 0;

    // Timing
    double target_seconds = hours * 3600.0;
    uint64_t t_start = mach_absolute_time();
    mach_timebase_info_data_t tb; mach_timebase_info(&tb);

    #define ELAPSED_S() ((double)(mach_absolute_time() - t_start) * tb.numer / tb.denom / 1e9)
    #define ELAPSED_MIN() (ELAPSED_S() / 60.0)

    // Checkpoint & log intervals
    int ckpt_interval = 500;
    int log_interval = 50;
    int plateau_window = 200; // steps to check for plateau

    // Rolling loss for plateau detection
    float loss_window[200];
    int loss_idx = 0;
    int loss_count = 0;

    fprintf(stderr, "ANEPROBE: ========================================\n");
    fprintf(stderr, "ANEPROBE: Target: %.1f hours (%.0f seconds)\n", hours, target_seconds);
    fprintf(stderr, "ANEPROBE: LR: %.1e, Plateau window: %d steps\n", lr, plateau_window);
    fprintf(stderr, "ANEPROBE: ========================================\n");

    // ===== MAIN TIME-BASED LOOP =====
    while (ELAPSED_S() < target_seconds) {
        uint64_t t_step = mach_absolute_time();

        // Set current LR on state
        s->lr = lr;

        float loss = ane_train_step(s);
        double step_ms = (double)(mach_absolute_time() - t_step) * tb.numer / tb.denom / 1e6;
        total_steps++;

        if (loss < best_loss) best_loss = loss;

        // Rolling loss window
        loss_window[loss_idx % plateau_window] = loss;
        loss_idx++;
        if (loss_count < plateau_window) loss_count++;

        // Log to file
        if (logFile) {
            fprintf(logFile, "%d,%.6f,%.6f,%.2e,%.1f,%d,%.1f,%d\n",
                total_steps, loss, best_loss, lr, step_ms, s->adam_t, ELAPSED_MIN(), phase);
            if (total_steps % 10 == 0) fflush(logFile);
        }

        // Console log
        if (total_steps <= 10 || total_steps % log_interval == 0) {
            double elapsed = ELAPSED_S();
            double remaining = target_seconds - elapsed;
            double steps_per_s = total_steps / elapsed;
            fprintf(stderr, "ANEPROBE: step %-6d loss=%.4f best=%.4f lr=%.1e adam=%d "
                "%.0fms/step %.1fsteps/s elapsed=%.0fm remaining=%.0fm phase=%d\n",
                total_steps, loss, best_loss, lr, s->adam_t,
                step_ms, steps_per_s, elapsed/60, remaining/60, phase);
        }

        // Checkpoint
        if (total_steps % ckpt_interval == 0) {
            fprintf(stderr, "ANEPROBE: [CHECKPOINT step %d, loss=%.4f, best=%.4f, lr=%.1e]\n",
                total_steps, loss, best_loss, lr);
            // Could call ane_train_save(s) here if checkpoint system is wired up
        }

        // Plateau detection: every plateau_window steps, check if loss improved
        if (total_steps > 0 && total_steps % plateau_window == 0 && loss_count >= plateau_window) {
            // Compare average of first half vs second half of window
            float avg_first = 0, avg_second = 0;
            int half = plateau_window / 2;
            for (int i = 0; i < half; i++) {
                avg_first += loss_window[(loss_idx - plateau_window + i) % plateau_window];
                avg_second += loss_window[(loss_idx - half + i) % plateau_window];
            }
            avg_first /= half;
            avg_second /= half;

            float improvement = (avg_first - avg_second) / avg_first;

            if (improvement < 0.001f) {
                // Less than 0.1% improvement → plateau
                plateau_count++;
                fprintf(stderr, "ANEPROBE: [PLATEAU #%d at step %d: avg %.4f→%.4f (%.2f%% improvement), "
                    "reducing LR %.1e→%.1e]\n",
                    plateau_count, total_steps, avg_first, avg_second, improvement*100, lr, lr*0.5f);

                lr *= 0.5f;
                if (lr < lr_min) {
                    // LR too low — reset to initial with new phase
                    phase++;
                    lr = 3e-4f * powf(0.7f, phase - 1); // each phase starts slightly lower
                    if (lr < lr_min) lr = lr_min;
                    phase_start_step = total_steps;
                    phase_start_loss = best_loss;
                    fprintf(stderr, "ANEPROBE: [NEW PHASE %d: LR reset to %.1e at step %d]\n",
                        phase, lr, total_steps);
                }
            } else {
                // Good progress — log it
                if (total_steps % (plateau_window * 2) == 0) {
                    fprintf(stderr, "ANEPROBE: [PROGRESS: %.2f%% improvement over last %d steps, LR=%.1e]\n",
                        improvement*100, plateau_window, lr);
                }
            }
        }
    }

    if (logFile) fclose(logFile);

    double total_s = ELAPSED_S();
    double total_min = total_s / 60.0;
    double total_hr = total_s / 3600.0;

    [log appendFormat:@"\n=== Timed Training Complete ===\n"];
    [log appendFormat:@"Duration: %.1f hours (%.0f minutes)\n", total_hr, total_min];
    [log appendFormat:@"Steps: %d (%.1f steps/s)\n", total_steps, total_steps/total_s];
    [log appendFormat:@"Best loss: %.4f\n", best_loss];
    [log appendFormat:@"Final loss: %.4f\n", s->last_loss];
    [log appendFormat:@"Final LR: %.1e\n", lr];
    [log appendFormat:@"Phases: %d\n", phase];
    [log appendFormat:@"Plateaus detected: %d\n", plateau_count];
    [log appendFormat:@"Adam updates: %d\n", s->adam_t];
    [log appendFormat:@"Compiles: %d\n", s->compile_count];
    [log appendFormat:@"Log: %@\n", logPath];

    fprintf(stderr, "ANEPROBE: ========================================\n");
    fprintf(stderr, "ANEPROBE: TRAINING COMPLETE\n");
    fprintf(stderr, "ANEPROBE: Duration: %.1f hours, %d steps\n", total_hr, total_steps);
    fprintf(stderr, "ANEPROBE: Best loss: %.4f, Final: %.4f\n", best_loss, s->last_loss);
    fprintf(stderr, "ANEPROBE: Phases: %d, Plateaus: %d, Final LR: %.1e\n", phase, plateau_count, lr);
    fprintf(stderr, "ANEPROBE: ========================================\n");
    fprintf(stderr, "ANEPROBE: === TIMED TRAINING COMPLETE ===\n");

    #undef ELAPSED_S
    #undef ELAPSED_MIN

    ane_train_free(s);
    return log;
    }
}
